Feature/json model context
cognizone/ng-cognizone pull request #14
Opened 2022-02-01 17:57 UTC by WilliamChelman

2022-02-11 12:18 UTC, farah111 approved these changes

2022-02-14 09:29 UTC, srikanthv02 requested changes

2022-02-14 09:29 UTC, srikanthv02 commented on README.md
> +- `JsonModel::@context` is not the same at all following same typing anymore. If ever you were using rootUri or isNew in there, you will need to find another way to get those info.
maybe :) 
`JsonModel::@context`- is not the same following the same typing anymore. If ever you were using rootUri or isNew, you will need to find another way to get that info.

2022-02-14 10:33 UTC, srikanthv02 approved these changes

2022-02-14 11:26 UTC, merged