Feature/cdk additions
cognizone/ng-cognizone pull request #66
Opened 2023-11-10 14:09 UTC by WilliamChelman

2023-11-14 12:52 UTC, farah111 approved these changes

2023-11-14 12:52 UTC, farah111 commented on README.md
> +```
and maybe we should mention AutoResizeHelper

2023-11-21 10:59 UTC, srikanthv02 requested changes

2023-11-21 10:59 UTC, srikanthv02 commented on libs/cdk/auto-resize-helper/auto-resize-helper.directive.ts
> +          this.debounceTime ? debounceTime(this.debounceTime) : tap(),
can we just write this as `debounceTime(this.debounceTime || 0)` ? 🤔

2023-11-21 11:53 UTC, srikanthv02 commented on libs/cdk/auto-resize-helper/auto-resize-helper.directive.ts
> +          this.debounceTime ? debounceTime(this.debounceTime) : tap(),
indeed, good point. Thanks :)

2023-11-21 11:53 UTC, srikanthv02 approved these changes

2023-11-21 12:08 UTC, merged