feat(legi-shared): adding option to show select dropdown icon for aut…
cognizone/ng-cognizone pull request #93
Opened 2024-12-02 13:00 UTC by srikanthv02

…ocomplete single and multi

2024-12-02 13:02 UTC, srikanthv02 commented on libs/legi-shared/autocomplete/autocomplete-multi/autocomplete-multi.component.ts
> +  optionType: "lookup" | 'raw' = "lookup";
issue being, when using a autocomplete multi, it was adding "create" to the mat-chip

2024-12-02 17:07 UTC, WilliamChelman requested changes

2024-12-02 17:07 UTC, WilliamChelman commented on libs/legi-shared/autocomplete/autocomplete-multi/autocomplete-multi.component.ts
> +  allowDropdownTrigger: boolean = false;
```suggestion
  profile: 'search' | 'select' = 'search';
```

2024-12-02 17:07 UTC, WilliamChelman commented on libs/legi-shared/autocomplete/autocomplete-multi/autocomplete-multi.component.ts
> +  optionType: "lookup" | 'raw' = "lookup";
```suggestion
  cacheOptions: boolean = true;
```
and in that method
```ts
private async storeValueOption(value: T): Promise<SelectOption<T> | undefined> {
    if (!this._optionsProvider || !value) return undefined;
    const hasOption = await firstValueFrom(this.optionsProvider.hasOptionFor(value));
    if (!hasOption) return undefined;
    const option = await firstValueFrom(this._optionsProvider.getValueOption(value));
    if(this.cacheOptions) this.storedValueOptions.push(option);
    return option;
  }
```

2024-12-02 17:07 UTC, WilliamChelman commented on libs/legi-shared/autocomplete/autocomplete-multi/autocomplete-multi.component.ts
> +    return this.storeValueOption(value);
This change can be reverted

2024-12-03 11:45 UTC, WilliamChelman approved these changes

2024-12-03 12:10 UTC, merged